drop table account;
create table account (
  ACCOUNTID VARCHAR2(20 CHAR)
, CUSTOMERCODE VARCHAR2(10 CHAR)
, BRANCHCODE VARCHAR2(10 CHAR)
, PRODUCT VARCHAR2(10 CHAR)
, DATEOPENED TIMESTAMP(6)
, SEGMENTATION VARCHAR2(100 CHAR) 
, CURRENCY VARCHAR2(10 CHAR)
, OPENEDBYTELLER VARCHAR2(50 CHAR)
, STATUS VARCHAR2(100 CHAR) 
, CREDITLIMIT NUMBER(24,6)
, DEBITLIMIT NUMBER(24,6)
, CREDITBASECODE VARCHAR2(50 CHAR)
, DEBITBASECODE VARCHAR2(50 CHAR)
, INTERESTSTARTDATE TIMESTAMP(6)
, DORMANTDATE TIMESTAMP(6)
, LOANPRINCIPALAMOUNT NUMBER(24,6)
, UBMODEOFOPERATION VARCHAR2(100 CHAR) 
, ENROLLMENTCODE VARCHAR2(50 CHAR)
, LASTTRANSACTIONDATE TIMESTAMP(6)
, DATEOFDORMANCY TIMESTAMP(6)
, DORMANTSTATUS VARCHAR2(10 CHAR)
, CLOSED VARCHAR2(10 CHAR)
, CLOSUREDATE TIMESTAMP(6)
, LOWESTBALANCE NUMBER(24,6)
, LOWESTBALANCEDATE TIMESTAMP(6)
, RECLASTMODIFIEDDATE TIMESTAMP(6)
, LASTCREDITTRANSDTTM TIMESTAMP(6)
, LASTDEBITTRANSDTTM TIMESTAMP(6) 
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_HIVE
  DEFAULT DIRECTORY "EXTERNAL_DIR"
  ACCESS PARAMETERS (
    com.oracle.bigdata.tablename=default.account
  )
);
EXIT
