drop table product;
create table product (
  PRODUCTID VARCHAR2(5 CHAR)
, PRODUCTNAME VARCHAR2(100 CHAR) 
, PARENTPRODUCT VARCHAR2(16 CHAR)
, SEGMENTATION VARCHAR2(50 CHAR)
, DORMANCY VARCHAR2(5 CHAR)
, MININTERESTRATE NUMBER
, MAXINTERESTRATE NUMBER
, DEBITLIMIT NUMBER(24,6)
, CREDITLIMIT NUMBER(24,6)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_HIVE
  DEFAULT DIRECTORY "EXTERNAL_DIR"
  ACCESS PARAMETERS (
    com.oracle.bigdata.tablename=default.product
  )
);
EXIT
