drop table transaction;
create table transaction (
  TRANSACTIONSRID VARCHAR2(50 CHAR)
, TRANSACTIONID VARCHAR2(30 CHAR)  
, SRNO NUMBER(38)         
, DEBITCREDITFLAG CHAR(1 CHAR)       
, VERSIONNUM NUMBER(38)         
, SYSTEMTRANS VARCHAR2(1 CHAR)   
, CODE VARCHAR2(3 CHAR)   
, EXCHANGERATE NUMBER(24,12)      
, NARRATION VARCHAR2(100 CHAR) 
, USERID VARCHAR2(30 CHAR)  
, POSTINGDATE VARCHAR2(19)       
, TRANSACTIONDATE VARCHAR2(19)       
, SOURCEBRANCH VARCHAR2(30 CHAR)  
, ACCOUNTID VARCHAR2(20 CHAR)  
, ISOCURRENCYCODE VARCHAR2(3 CHAR)   
, BOOKBALANCE NUMBER(24,6)       
, AMOUNTCREDIT NUMBER(24,6)       
, AMOUNTDEBIT NUMBER(24,6)       
, ORIGINALAMOUNT NUMBER(24,6)       
, AMOUNT NUMBER(24,6)       
, UBCHANNELID VARCHAR2(20 CHAR)  
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_HIVE
  DEFAULT DIRECTORY "EXTERNAL_DIR"
  ACCESS PARAMETERS (
    com.oracle.bigdata.tablename=default.transaction
  )
);
EXIT
