drop table balance;
create table balance (
  ACCOUNTID VARCHAR2(20 CHAR)
, PRODUCTID VARCHAR2(10)
, CLEAREDBALANCE NUMBER(24,6)
, CLOSINGBALANCE NUMBER(24,6)
, DATEOFBALANCE TIMESTAMP(6)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_HIVE
  DEFAULT DIRECTORY "EXTERNAL_DIR"
  ACCESS PARAMETERS (
    com.oracle.bigdata.tablename=default.balance
  )
);
EXIT
