drop table customer;
create table customer (
  CUSTOMERCODE VARCHAR2(25 CHAR)
, NRCNO VARCHAR2(256 CHAR) 
, FIRSTNAME VARCHAR2(60 CHAR)
, LASTNAME VARCHAR2(60 CHAR)
, SHORTNAME VARCHAR2(60 CHAR)
, DOB VARCHAR2(10)
, GENDER VARCHAR2(255 CHAR) 
, ADDRESSLINE2 VARCHAR2(256 CHAR) 
, ADDRESSLINE3 VARCHAR2(256 CHAR) 
, ADDRESSLINE4 VARCHAR2(256 CHAR) 
, ADDRESSLINE5 VARCHAR2(256 CHAR) 
, SEGMENTATION VARCHAR2(50 CHAR)
, BLACKLISTED VARCHAR2(3)
, CUSTOMERTYPE VARCHAR2(10)
, CUSTOMERSUBTYPE VARCHAR2(255 CHAR) 
, UBRELATIONSHIPMGRID VARCHAR2(30 CHAR)
, DATECREATED VARCHAR2(19)
, DATEMODIFIED VARCHAR2(19)
, SUBCATEGORY VARCHAR2(255 CHAR) 
, KYCSTATUS VARCHAR2(255 CHAR) 
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_HIVE
  DEFAULT DIRECTORY "EXTERNAL_DIR"
  ACCESS PARAMETERS (
    com.oracle.bigdata.tablename=default.customer
  )
);
EXIT
